// Code generated by scripts/generate_schema_ids.py; DO NOT EDIT.
package contracts

const AnthropicMessagesCommonSchema = "urn:operator:schema:anthropic-messages-common:v1alpha1"

const AnthropicMessagesRequestSchema = "urn:operator:schema:anthropic-messages-request:v1alpha1"

const AnthropicMessagesResponseSchema = "urn:operator:schema:anthropic-messages-response:v1alpha1"

const AssessmentCommonSchema = "urn:operator:schema:assessment-common:v1alpha1"

const ConclusionBindingSchema = "urn:operator:schema:conclusion-binding:v1alpha1"

const ContractPackageSchema = "urn:operator:schema:contract-package:v1alpha1"

const EngineArtifactBeginRequestSchema = "urn:operator:schema:engine-artifact-begin-request:v1alpha1"

const EngineArtifactBeginResultSchema = "urn:operator:schema:engine-artifact-begin-result:v1alpha1"

const EngineArtifactCommitRequestSchema = "urn:operator:schema:engine-artifact-commit-request:v1alpha1"

const EngineArtifactCommitResultSchema = "urn:operator:schema:engine-artifact-commit-result:v1alpha1"

const EngineArtifactPutPartRequestSchema = "urn:operator:schema:engine-artifact-put-part-request:v1alpha1"

const EngineArtifactPutPartResultSchema = "urn:operator:schema:engine-artifact-put-part-result:v1alpha1"

const EngineAttemptRequestSchema = "urn:operator:schema:engine-attempt-request:v1alpha2"

const EngineAttemptResultSchema = "urn:operator:schema:engine-attempt-result:v1alpha2"

const EngineConclusionSchema = "urn:operator:schema:engine-conclusion:v1alpha2"

const EngineContextSchema = "urn:operator:schema:engine-context:v1alpha1"

const EngineGuestControlSchema = "urn:operator:schema:engine-guest-control:v1alpha1"

const EngineHostControlSchema = "urn:operator:schema:engine-host-control:v1alpha1"

const EngineInjectionDeleteRequestSchema = "urn:operator:schema:engine-injection-delete-request:v1alpha1"

const EngineInjectionDeleteResultSchema = "urn:operator:schema:engine-injection-delete-result:v1alpha1"

const EngineModelGenerateRequestSchema = "urn:operator:schema:engine-model-generate-request:v1alpha1"

const EngineModelGenerateResultSchema = "urn:operator:schema:engine-model-generate-result:v1alpha1"

const EngineObservationReadRequestSchema = "urn:operator:schema:engine-observation-read-request:v1alpha1"

const EngineObservationReadResultSchema = "urn:operator:schema:engine-observation-read-result:v1alpha1"

const EnginePipeRequestSchema = "urn:operator:schema:engine-pipe-request:v1alpha1"

const EnginePipeResponseSchema = "urn:operator:schema:engine-pipe-response:v1alpha1"

const EngineRecordAppendRequestSchema = "urn:operator:schema:engine-record-append-request:v1alpha1"

const EngineRecordAppendResultSchema = "urn:operator:schema:engine-record-append-result:v1alpha1"

const EngineRequestStopRequestSchema = "urn:operator:schema:engine-request-stop-request:v1alpha1"

const EngineRequestStopResultSchema = "urn:operator:schema:engine-request-stop-result:v1alpha1"

const EngineRestoreRequestSchema = "urn:operator:schema:engine-restore-request:v1alpha1"

const EngineRestoreResultSchema = "urn:operator:schema:engine-restore-result:v1alpha1"

const EngineSnapshotInspectRequestSchema = "urn:operator:schema:engine-snapshot-inspect-request:v1alpha1"

const EngineSnapshotInspectResultSchema = "urn:operator:schema:engine-snapshot-inspect-result:v1alpha1"

const EngineSnapshotListRequestSchema = "urn:operator:schema:engine-snapshot-list-request:v1alpha1"

const EngineSnapshotListResultSchema = "urn:operator:schema:engine-snapshot-list-result:v1alpha1"

const EngineSnapshotRequestSchema = "urn:operator:schema:engine-snapshot-request:v1alpha1"

const EngineSnapshotResultSchema = "urn:operator:schema:engine-snapshot-result:v1alpha1"

const EngineSpoolAckSchema = "urn:operator:schema:engine-spool-ack:v1alpha1"

const FeedbackManifestSchema = "urn:operator:schema:feedback-manifest:v1alpha1"

const HarnessLoopLimitsSchema = "urn:operator:schema:harness-loop-limits:v1alpha1"

const InputTreeManifestSchema = "urn:operator:schema:input-tree-manifest:v1alpha1"

const ModelCodecPolicySchema = "urn:operator:schema:model-codec-policy:v1alpha1"

const ModelToolNotExecutedResultSchema = "urn:operator:schema:model-tool-not-executed-result:v1alpha1"

const ObservationSelectionSchema = "urn:operator:schema:observation-selection:v1alpha1"

const OpenaiChatCommonSchema = "urn:operator:schema:openai-chat-common:v1alpha1"

const OpenaiChatRequestSchema = "urn:operator:schema:openai-chat-request:v1alpha1"

const OpenaiChatResponseSchema = "urn:operator:schema:openai-chat-response:v1alpha1"

const OperationErrorSchema = "urn:operator:schema:operation-error:v1alpha1"

const OperationRegistrySchema = "urn:operator:schema:operation-registry:v1alpha1"

const PromptProvenanceSchema = "urn:operator:schema:prompt-provenance:v1alpha1"

const RemainingLimitsSchema = "urn:operator:schema:remaining-limits:v1alpha1"

const ScenarioBundleSchema = "urn:operator:schema:scenario-bundle:v1alpha1"

const SkillManifestSchema = "urn:operator:schema:skill-manifest:v1alpha1"

const SkillSetManifestSchema = "urn:operator:schema:skill-set-manifest:v1alpha1"

const SnapshotMetadataSchema = "urn:operator:schema:snapshot-metadata:v1alpha1"

const StartupCommonSchema = "urn:operator:schema:startup-common:v1alpha1"

const TargetCapabilityManifestSchema = "urn:operator:schema:target-capability-manifest:v1alpha1"

const WireCommonSchema = "urn:operator:schema:wire-common:v1alpha1"
