// Code generated by scripts/generate_schema_ids.py; DO NOT EDIT.
package contracts

const EngineAttemptRequestSchema = "urn:operator:schema:engine-attempt-request:v1alpha2"

const EngineAttemptResultSchema = "urn:operator:schema:engine-attempt-result:v1alpha2"

const EngineInjectionDeleteRequestSchema = "urn:operator:schema:engine-injection-delete-request:v1alpha1"

const EngineInjectionDeleteResultSchema = "urn:operator:schema:engine-injection-delete-result:v1alpha1"

const EngineObservationReadRequestSchema = "urn:operator:schema:engine-observation-read-request:v1alpha1"

const EngineObservationReadResultSchema = "urn:operator:schema:engine-observation-read-result:v1alpha1"

const FeedbackManifestSchema = "urn:operator:schema:feedback-manifest:v1alpha1"

const HarnessLoopLimitsSchema = "urn:operator:schema:harness-loop-limits:v1alpha1"

const ModelToolNotExecutedResultSchema = "urn:operator:schema:model-tool-not-executed-result:v1alpha1"

const ObservationSelectionSchema = "urn:operator:schema:observation-selection:v1alpha1"

const ScenarioBundleSchema = "urn:operator:schema:scenario-bundle:v1alpha1"

const TargetCapabilityManifestSchema = "urn:operator:schema:target-capability-manifest:v1alpha1"
