"""Generate closed ordinary envelopes from the checked-in operation registry."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "schemas"
COMMON = "urn:operator:schema:wire-common:v1alpha1#/$defs/"


def render(direction, operations):
    props = {
        "api_version": {"const": "operator.dev/engine-pipe/v1alpha1"},
        "kind": {"const": direction},
        "seq": {"$ref": COMMON + "integer"},
        "campaign_id": {"$ref": COMMON + "id"},
        "launch_id": {"$ref": COMMON + "id"},
        "run_revision": {"$ref": COMMON + "integer"},
        "call_id": {"$ref": COMMON + "id"},
        "operation_id": {"$ref": COMMON + "id"},
        "operation": {"enum": [op["name"] for op in operations]},
    }
    required = list(props)
    if direction == "request":
        props.update(timeout_ms={"type": "integer", "minimum": 1, "maximum": (1 << 53) - 1}, body={})
        required.extend(["timeout_ms", "body"])
    else:
        props.update(result={}, error={})
    branches = []
    for operation in operations:
        typed = {"operation": {"const": operation["name"]}}
        if direction == "request":
            typed["body"] = {"$ref": operation["request_schema"]}
        else:
            typed["result"] = {"$ref": operation["result_schema"]}
            typed["error"] = {
                "allOf": [
                    {"$ref": operation["error_schema"]},
                    {"properties": {"code": {"enum": operation["error_codes"]}}},
                ]
            }
        branches.append({"properties": typed})
    document = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"urn:operator:schema:engine-pipe-{direction}:v1alpha1",
        "$comment": "Generated by scripts/generate_envelopes.py from operations.json; do not edit.",
        "type": "object", "additionalProperties": False,
        "properties": props, "required": required, "oneOf": branches,
    }
    if direction == "response":
        document["allOf"] = [{"oneOf": [{"required": ["result"]}, {"required": ["error"]}]}]
    return json.dumps(document, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    operations = json.loads((ROOT / "operations.json").read_text())["operations"]
    names = [op["name"] for op in operations]
    if names != sorted(set(names)):
        raise SystemExit("Operations must be unique and sorted")
    for direction in ("request", "response"):
        path = ROOT / f"engine-pipe-{direction}.schema.json"
        content = render(direction, operations)
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated schema: {path.name}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
