"""Generate stable schema URI constants from the installed catalog (stdlib only)."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    catalog = json.loads((ROOT / "schemas/catalog.json").read_text())
    go = ["// Code generated by scripts/generate_schema_ids.py; DO NOT EDIT.", "package contracts", ""]
    python = ['"""Generated by scripts/generate_schema_ids.py; do not edit."""', ""]
    for uri in sorted(catalog):
        stem = catalog[uri].removesuffix(".schema.json")
        go_name = "".join(word.title() for word in stem.split("-")) + "Schema"
        python_name = stem.replace("-", "_").upper() + "_SCHEMA"
        go.append(f"const {go_name} = {json.dumps(uri)}")
        go.append("")
        python.append(f"{python_name} = {json.dumps(uri)}")
    outputs = {
        ROOT / "contracts/schema_ids.go": "\n".join(go),
        ROOT / "contracts/python/operator_contracts/schema_ids.py": "\n".join(python) + "\n",
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated file: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
