// Generate the Python path repertoire/folding tables from the pinned Go Unicode
// 15.0 profile. NFC is stable for this assigned repertoire on later Python UCDs.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"unicode"

	"golang.org/x/text/cases"
	"golang.org/x/text/unicode/norm"
	"golang.org/x/text/unicode/rangetable"
)

func main() {
	check := flag.Bool("check", false, "check generated tables")
	flag.Parse()
	if cases.UnicodeVersion != "15.0.0" || norm.Version != "15.0.0" {
		panic("path profile requires Unicode 15.0.0")
	}
	assigned := rangetable.Assigned("15.0.0")
	folder := cases.Fold()
	var ranges [][2]int
	var folds []string
	start := -1
	for cp := 0; cp <= unicode.MaxRune+1; cp++ {
		present := cp <= unicode.MaxRune && unicode.Is(assigned, rune(cp)) && !(cp >= 0xd800 && cp <= 0xdfff)
		if present && start < 0 {
			start = cp
		}
		if !present && start >= 0 {
			ranges = append(ranges, [2]int{start, cp - 1})
			start = -1
		}
		if present {
			s := string(rune(cp))
			fold := folder.String(s)
			if fold != s {
				encoded, _ := json.Marshal(fold)
				folds = append(folds, fmt.Sprintf("    %d: %s,\n", cp, encoded))
			}
		}
	}
	var output bytes.Buffer
	output.WriteString("\"\"\"Generated by scripts/generate_path_unicode.go; Unicode 15.0 path profile.\"\"\"\nfrom bisect import bisect_right\n\nRANGES = (\n")
	for _, r := range ranges {
		fmt.Fprintf(&output, "    (%d, %d),\n", r[0], r[1])
	}
	output.WriteString(")\nSTARTS = tuple(start for start, _ in RANGES)\nFOLDS = {\n")
	for _, line := range folds {
		output.WriteString(line)
	}
	output.WriteString("}\n\n\ndef assigned(char):\n    point = ord(char)\n    index = bisect_right(STARTS, point) - 1\n    return index >= 0 and point <= RANGES[index][1]\n\n\ndef casefold(value):\n    return value.translate(FOLDS)\n")
	path := "contracts/python/operator_contracts/path_unicode.py"
	if *check {
		actual, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(actual, output.Bytes()) {
			fmt.Fprintln(os.Stderr, "stale Unicode path tables: run make generate")
			os.Exit(1)
		}
	} else if err := os.WriteFile(path, output.Bytes(), 0644); err != nil {
		panic(err)
	}
}
